export const table = [
  {
    codeAgent: '',
    name: '',
    shop: '',
    region: '',
    sat: '',
    mtd_last_month: '',
    mtd_this_month: '',
    gap_visit_percent: '',
    object_visited: '',
    object_visited_by_other: '',
    no_visited_object: '',
    tot_track: '',
    vm_target_in_mtd: '',
    percent_visit_vs_target: '',
    current_visit_target: '',
    notes_on_visits: '',
    percent_realisation_cash: '',
    categorisable: '',
    categorie: '',
    a_tracker_pour_completer: '',
    rien_payer: '',
    eteint_aujourdhui: '',
    no_action_potentiel_default: '',
    action_potentiel_default: '',
    object_potentiel_default: '',
    payed_after_visit: '',
    payed_before_visit: '',
    percent_realisation_potentiel_default: ''
  }
];
export const table_keys = [
  { id: '0', display: 'codeAgent' },
  { id: '25', display: 'name' },
  { id: '26', display: 'shop' },
  { id: '27', display: 'region' },
  { id: '1', display: 'sat' },
  { id: '2', display: 'mtd_last_month' },
  { id: '3', display: 'mtd_this_month' },
  { id: '4', display: 'gap_visit_percent' },
  { id: '5', display: 'object_visited' },
  { id: '6', display: 'object_visited_by_other' },
  { id: '7', display: 'no_visited_object' },
  { id: '8', display: 'tot_track' },
  { id: '9', display: 'vm_target_in_mtd' },
  { id: '10', display: 'percent_visit_vs_target' },
  { id: '11', display: 'current_visit_target' },
  { id: '12', display: 'notes_on_visits' },
  { id: '13', display: 'percent_realisation_cash' },
  { id: '14', display: 'categorisable' },
  { id: '15', display: 'categorie' },
  { id: '16', display: 'a_tracker_pour_completer' },
  { id: '17', display: 'rien_payer' },
  { id: '18', display: 'eteint_aujourdhui' },
  { id: '19', display: 'no_action_potentiel_default' },
  { id: '20', display: 'action_potentiel_default' },
  { id: '21', display: 'object_potentiel_default' },
  { id: '22', display: 'payed_after_visit' },
  { id: '23', display: 'payed_before_visit' },
  { id: '24', display: 'percent_realisation_potentiel_default' }
];
export const table_keys_only = [
  'codeAgent',
  'name',
  'shop',
  'region',
  'sat',
  'mtd_last_month',
  'mtd_this_month',
  'gap_visit_percent',
  'object_visited',
  'object_visited_by_other',
  'no_visited_object',
  'tot_track',
  'vm_target_in_mtd',
  'percent_visit_vs_target',
  'current_visit_target',
  'notes_on_visits',
  'percent_realisation_cash',
  'categorisable',
  'categorie',
  'a_tracker_pour_completer',
  'rien_payer',
  'eteint_aujourdhui',
  'no_action_potentiel_default',
  'action_potentiel_default',
  'object_potentiel_default',
  'payed_after_visit',
  'payed_before_visit',
  'percent_realisation_potentiel_default'
];
export const dataFilter = [
  { id: 1, title: 'Staff only who can submit feedbacks', value: ['staff'] },
  { id: 2, title: 'Staff width agents can submit feedbacks', value: ['staff', 'agent'] },
  { id: 3, title: 'Agent only who can submit feedbacks', value: ['agent'] }
];
